backend:
  name: github
  repo: iuliiashimanskaia-ship-it/galaxy-home # Твой репозиторий
  branch: master # Или main, проверь как называется ветка

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "houses"
    label: "Наши дома (Товары)"
    folder: "src/content/houses"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Цена", name: "price", widget: "number" }
      - { label: "Описание", name: "body", widget: "markdown" }
      - { label: "Фото", name: "image", widget: "image" }